package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class HashEquiJoin extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate p;
    private DbIterator child1;
    private DbIterator child2;
    private HashMap<Field,ArrayList<Tuple> > map;
    private Tuple now2;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public HashEquiJoin(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p=p;
        this.child1 = child1;
        this.child2 = child2;
        map = new HashMap<>();
    }

    public JoinPredicate getJoinPredicate() {
        return p;
    }

    public TupleDesc getTupleDesc() {
        return TupleDesc.merge(child1.getTupleDesc(),child2.getTupleDesc());
    }
    
    public String getJoinField1Name()
    {
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    public String getJoinField2Name()
    {
        return child2.getTupleDesc().getFieldName(p.getField2());
    }
    
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        map.clear();
        listIt = null;
        now2 = null;
        child1.open();
        child2.open();
        while (child1.hasNext()) {
            Tuple tmp = child1.next();
            Field key = tmp.getField(p.getField1());
            if (!map.containsKey(key)) {
                map.put(key,new ArrayList<>());
            }
            map.get(key).add(tmp);
        }
        super.open();
    }

    public void close() {
        super.close();
        map.clear();
        listIt = null;
        now2 = null;
        child2.close();
        child1.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
    }

    transient Iterator<Tuple> listIt = null;

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, there will be two copies of the join attribute in
     * the results. (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if (!(listIt!=null && listIt.hasNext())) {
            boolean changed = false;
            while (child2.hasNext()) {
                now2 = child2.next();
                if (map.containsKey(now2.getField(p.getField2()))) {
                    listIt = map.get(now2.getField(p.getField2())).iterator();
                    changed = true;
                    break;
                }
            }
            if (!changed) return null;
        }
        return Tuple.merge(listIt.next(),now2);
    }

    @Override
    public DbIterator[] getChildren() {
        DbIterator[] ans = new DbIterator[2];
        ans[0]=child1;
        ans[1]=child2;
        return ans;
    }

    @Override
    public void setChildren(DbIterator[] children) {
        child1 = children[0];
        child2 = children[1];
    }
    
}
